import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { BookOpen, Check, GraduationCap, Pencil, Users } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import MedaadLogo from "@/components/MedaadLogo";

export default function AuthPage({ mode }: { mode: "login" | "register" }) {
  const [role, setRole] = useState<"student" | "teacher">("student");
  const register = mode === "register";
  return <div dir="rtl" className="min-h-screen bg-[#f7fafb] lg:grid lg:grid-cols-[.9fr_1.1fr]">
    <div className="hidden bg-[#123f46] p-12 text-white lg:flex lg:flex-col lg:justify-between"><MedaadLogo /><div className="max-w-md"><div className="mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-white/10"><Pencil className="h-7 w-7 text-[#f4ae6e]" /></div><h1 className="text-4xl font-black leading-[1.4]">یادگیری خوب،<br /><span className="text-[#9ddbd6]">با یک سؤال خوب شروع می‌شود.</span></h1><p className="mt-6 leading-8 text-[#b3d0d0]">در مداد سؤال‌هایت را به مسیر یادگیری تبدیل کن؛ با توضیح، تمرین و همراهی.</p><div className="mt-10 space-y-4 text-sm text-[#c6e3e1]"><div className="flex items-center gap-3"><Check className="h-4 w-4 text-[#f4ae6e]" /> توضیح مرحله‌به‌مرحله و قابل فهم</div><div className="flex items-center gap-3"><Check className="h-4 w-4 text-[#f4ae6e]" /> فضای مخصوص دانش‌آموز و معلم</div><div className="flex items-center gap-3"><Check className="h-4 w-4 text-[#f4ae6e]" /> ابزارهای واقعی برای مطالعه</div></div></div><p className="text-xs text-[#7ca8a8]">هر چیزی که نمی‌فهمی، بپرس.</p></div>
    <div className="flex min-h-screen items-center justify-center px-5 py-10"><div className="w-full max-w-md"><div className="mb-10 flex items-center justify-between lg:hidden"><MedaadLogo /><Link href="/" className="text-sm font-bold text-[#087f8c]">بازگشت</Link></div><div className="mb-8"><p className="mb-3 text-sm font-black text-[#f08f4f]">{register ? "به جمع مدادی‌ها خوش آمدی" : "خوش برگشتی"}</p><h1 className="text-3xl font-black text-[#163c41]">{register ? "حساب خودت را بساز" : "ورود به مداد"}</h1><p className="mt-3 text-sm leading-7 text-[#70868a]">{register ? "نقش خودت را انتخاب کن تا فضای مناسب را برایت آماده کنیم." : "برای ادامه به حساب کاربری‌ات وارد شو."}</p></div>{register && <div className="mb-7 grid grid-cols-2 gap-3"><button onClick={() => setRole("student")} className={`rounded-2xl border p-4 text-right transition ${role === "student" ? "border-[#8ed3d0] bg-[#eaf8f6]" : "border-[#dce8e9] bg-white"}`}><GraduationCap className={`mb-4 h-6 w-6 ${role === "student" ? "text-[#087f8c]" : "text-[#93a9ac]"}`} /><p className="text-sm font-extrabold text-[#315a60]">دانش‌آموز</p><p className="mt-1 text-[11px] leading-5 text-[#809598]">یادگیری و تمرین</p></button><button onClick={() => setRole("teacher")} className={`rounded-2xl border p-4 text-right transition ${role === "teacher" ? "border-[#f5c28e] bg-[#fff5eb]" : "border-[#dce8e9] bg-white"}`}><Users className={`mb-4 h-6 w-6 ${role === "teacher" ? "text-[#d77b35]" : "text-[#93a9ac]"}`} /><p className="text-sm font-extrabold text-[#315a60]">معلم</p><p className="mt-1 text-[11px] leading-5 text-[#809598]">کلاس و محتوا</p></button></div>}
      <Button onClick={() => { if (register) localStorage.setItem("medaad-intended-role", role); startLogin(); }} className="h-13 w-full rounded-xl bg-[#087f8c] font-bold shadow-[0_10px_22px_rgba(8,127,140,.18)] hover:bg-[#076d78]">{register ? `ساخت حساب ${role === "teacher" ? "معلم" : "دانش‌آموز"}` : "ورود امن به مداد"}</Button><p className="mt-7 text-center text-xs leading-6 text-[#8aa0a3]">با ورود، شرایط استفاده و حریم خصوصی مداد را می‌پذیری.</p><p className="mt-8 text-center text-sm text-[#70868a]">{register ? "قبلاً حساب ساخته‌ای؟" : "هنوز حساب نداری؟"} <Link href={register ? "/login" : "/register"} className="font-extrabold text-[#087f8c]">{register ? "وارد شو" : "ثبت‌نام کن"}</Link></p><div className="mt-12 flex items-center justify-center gap-5 text-xs text-[#93a9ac]"><span className="flex items-center gap-1.5"><BookOpen className="h-3.5 w-3.5" /> فارسی و راست‌به‌چپ</span><span>•</span><span>داده‌های خصوصی</span></div></div></div>
  </div>;
}
