import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { File, FileText, Image, Loader2, MoreHorizontal, Sparkles, UploadCloud } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";
import { PageHeader, EmptyState } from "./Shared";
import { Streamdown } from "streamdown";

export default function FilesPage({ teacher = false }: { teacher?: boolean }) {
  const inputRef = useRef<HTMLInputElement>(null); const files = trpc.files.list.useQuery(undefined, { retry: false }); const upload = trpc.files.upload.useMutation({ onSuccess: () => { files.refetch(); toast.success("فایل با موفقیت ذخیره شد."); }, onError: e => toast.error(e.message) }); const summarize = trpc.files.summarize.useMutation({ onSuccess: data => setResult(data.answer), onError: e => toast.error(e.message) }); const [result, setResult] = useState(""); const [text, setText] = useState("");
  const handle = async (file?: File) => { if (!file) return; const allowed = ["application/pdf", "image/jpeg", "image/png", "image/webp", "text/plain"]; if (!allowed.includes(file.type)) { toast.error("فایلی با این فرمت پشتیبانی نمی‌شود."); return; } if (file.size > 10_000_000) { toast.error("حجم فایل بیش از حد مجاز است."); return; } const reader = new FileReader(); reader.onload = () => upload.mutate({ name: file.name, mimeType: file.type as any, size: file.size, data: String(reader.result).split(",")[1] ?? "" }); reader.readAsDataURL(file); };
  return <div><PageHeader eyebrow={teacher ? "محتوای آموزشی" : "کتابخانه شخصی"} title="فایل‌های من" description="جزوه‌ها، عکس‌ها و مطالب درسی‌ات را یکجا نگه دار و هر وقت خواستی از آن‌ها یاد بگیر." action={<Button onClick={() => inputRef.current?.click()} disabled={upload.isPending} className="h-11 rounded-xl bg-[#087f8c] font-bold hover:bg-[#076d78]"><input ref={inputRef} type="file" className="hidden" accept="application/pdf,image/jpeg,image/png,image/webp,text/plain" onChange={e => handle(e.target.files?.[0])} />{upload.isPending ? <Loader2 className="ml-2 h-4 w-4 animate-spin" /> : <UploadCloud className="ml-2 h-4 w-4" />} بارگذاری فایل</Button>} />
    <div className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="rounded-[1.5rem] border border-[#dce8e9] bg-white p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-black text-[#315a60]">کتابخانه</h2><span className="text-xs text-[#8aa0a3]">{files.data?.length ?? 0} فایل</span></div>{files.data?.length ? <div className="grid gap-3 sm:grid-cols-2">{files.data.map(file => <div key={file.id} className="group rounded-2xl border border-[#edf2f2] bg-[#fbfdfd] p-4 transition hover:border-[#bfe4e1]"><div className="flex items-start justify-between gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e7f0ff] text-[#4c72bd]">{file.mimeType.startsWith("image") ? <Image className="h-5 w-5" /> : <FileText className="h-5 w-5" />}</div><button className="rounded-lg p-1 text-[#a1b2b4] hover:bg-[#edf5f5]" aria-label="گزینه‌های فایل"><MoreHorizontal className="h-4 w-4" /></button></div><p className="mt-4 truncate text-sm font-extrabold text-[#315a60]" title={file.name}>{file.name}</p><p className="mt-1 text-[11px] text-[#91a4a7]">{Math.round(file.size / 1024)} کیلوبایت • {new Date(file.createdAt).toLocaleDateString("fa-IR")}</p></div>)}</div> : <EmptyState title="کتابخانه‌ات هنوز خالی است" description="یک جزوه یا تصویر سؤال بارگذاری کن تا ابزارهای یادگیری مداد روی آن در دسترس باشند." actionLabel="بارگذاری اولین فایل" />}</section><section className="rounded-[1.5rem] border border-[#f0d6b8] bg-[#fffaf5] p-5 sm:p-7"><div className="mb-5 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#fff0df] text-[#d77b35]"><Sparkles className="h-5 w-5" /></div><div><h2 className="text-lg font-black text-[#69482f]">از متن یاد بگیر</h2><p className="mt-1 text-xs text-[#a47b5a]">متن را بچسبان و یک خروجی آموزشی بگیر.</p></div></div><textarea value={text} onChange={e => setText(e.target.value)} placeholder="متن جزوه یا بخشی از درس را اینجا وارد کن..." className="min-h-[170px] w-full resize-y rounded-xl border border-[#f1d7ba] bg-white p-3 text-sm leading-7 text-[#69482f] outline-none placeholder:text-[#c2a68b] focus:border-[#eab67f]" /><div className="mt-3 grid grid-cols-2 gap-2"><Button variant="outline" onClick={() => summarize.mutate({ text, action: "summary" })} disabled={text.length < 20 || summarize.isPending} className="h-10 rounded-xl border-[#efd5b7] bg-white text-xs text-[#9a5b2d]">خلاصه کن</Button><Button variant="outline" onClick={() => summarize.mutate({ text, action: "questions" })} disabled={text.length < 20 || summarize.isPending} className="h-10 rounded-xl border-[#efd5b7] bg-white text-xs text-[#9a5b2d]">سؤال بساز</Button></div>{result && <div className="mt-4 rounded-xl bg-white p-4 text-xs leading-7 text-[#69482f]"><Streamdown>{result}</Streamdown></div>}</section></div>
  </div>;
}
