import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Award, CheckCircle2, ClipboardList, Clock3, Loader2, Plus, Sparkles, XCircle } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { PageHeader, EmptyState } from "./Shared";

export default function QuizzesPage({ teacher = false }: { teacher?: boolean }) {
  const quizzes = trpc.quizzes.list.useQuery({ teacher }, { retry: false }); const [selected, setSelected] = useState<number>(); const [answers, setAnswers] = useState<Record<string, string>>({}); const [result, setResult] = useState<{ score: number; total: number; quizTitle: string }>(); const detail = trpc.quizzes.get.useQuery({ id: selected! }, { enabled: Boolean(selected), retry: false }); const attempt = trpc.quizzes.attempt.useMutation({ onSuccess: data => setResult(data), onError: e => toast.error(e.message) });
  if (selected && detail.data) return <div><button onClick={() => { setSelected(undefined); setResult(undefined); setAnswers({}); }} className="mb-6 text-sm font-bold text-[#087f8c]">← بازگشت به فهرست آزمون‌ها</button><PageHeader eyebrow="آزمون" title={detail.data!.title} description={`${detail.data!.subject}${detail.data!.topic ? ` • ${detail.data!.topic}` : ""}`} />{result ? <div className="max-w-2xl rounded-[1.5rem] border border-[#cbe6df] bg-[#effaf7] p-8 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-white text-[#4a9667]"><Award className="h-8 w-8" /></div><h2 className="mt-5 text-2xl font-black text-[#27654f]">نتیجه آزمون</h2><p className="mt-3 text-4xl font-black text-[#087f8c]">{result.score} <span className="text-lg text-[#6f9690]">از {result.total}</span></p><Button onClick={() => { setSelected(undefined); setResult(undefined); }} className="mt-7 rounded-xl bg-[#087f8c] font-bold hover:bg-[#076d78]">بازگشت به آزمون‌ها</Button></div> : <div className="max-w-3xl space-y-4">{detail.data!.questions.map((q, index) => <div key={q.id} className="rounded-[1.3rem] border border-[#dce8e9] bg-white p-5"><div className="mb-4 flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[#eaf8f6] text-xs font-black text-[#087f8c]">{index + 1}</span><p className="text-sm font-extrabold leading-7 text-[#315a60]">{q.question}</p></div>{q.options?.length ? <div className="grid gap-2 sm:grid-cols-2">{q.options.map(option => <label key={option} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-xs font-bold transition ${answers[String(q.id)] === option ? "border-[#8ed3d0] bg-[#eaf8f6] text-[#087f8c]" : "border-[#edf2f2] text-[#668085] hover:bg-[#fbfdfd]"}`}><input type="radio" name={`q-${q.id}`} value={option} checked={answers[String(q.id)] === option} onChange={e => setAnswers({ ...answers, [String(q.id)]: e.target.value })} className="accent-[#087f8c]" />{option}</label>)}</div> : <textarea value={answers[String(q.id)] ?? ""} onChange={e => setAnswers({ ...answers, [String(q.id)]: e.target.value })} placeholder="پاسخت را بنویس..." className="min-h-24 w-full rounded-xl border border-[#dce8e9] p-3 text-sm outline-none focus:border-[#71c4c0]" />}</div>)}<Button onClick={() => attempt.mutate({ quizId: detail.data!.id, answers })} disabled={attempt.isPending} className="h-12 rounded-xl bg-[#087f8c] px-6 font-bold hover:bg-[#076d78]">{attempt.isPending ? <Loader2 className="ml-2 h-4 w-4 animate-spin" /> : <CheckCircle2 className="ml-2 h-4 w-4" />} ثبت پاسخ‌ها</Button></div>}</div>;
  return <div><PageHeader eyebrow={teacher ? "کارگاه سنجش" : "مرور و سنجش"} title={teacher ? "آزمون‌ها" : "آزمون‌های من"} description={teacher ? "آزمون‌ها را بساز، بازبینی کن و بعد منتشر کن." : "با آزمون‌های منتشرشده دانسته‌هایت را محک بزن."} action={teacher ? <Button onClick={() => toast.info("ساخت آزمون از روی فایل در مرحله بعد از بارگذاری متن در دسترس است.")} className="h-11 rounded-xl bg-[#087f8c] font-bold hover:bg-[#076d78]"><Plus className="ml-2 h-4 w-4" /> آزمون جدید</Button> : undefined} />{quizzes.data?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{quizzes.data.map(quiz => <button key={quiz.id} onClick={() => setSelected(quiz.id)} className="interactive text-right rounded-[1.35rem] border border-[#deeaeb] bg-white p-5"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#eeeaff] text-[#7562c3]"><ClipboardList className="h-5 w-5" /></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${quiz.status === "published" ? "bg-[#e3f4e9] text-[#4a9667]" : "bg-[#fff0df] text-[#a56936]"}`}>{quiz.status === "published" ? "منتشرشده" : "پیش‌نویس"}</span></div><h3 className="mt-5 text-base font-black text-[#315a60]">{quiz.title}</h3><p className="mt-2 text-xs text-[#84999c]">{quiz.subject}{quiz.topic ? ` • ${quiz.topic}` : ""}</p><div className="mt-5 flex items-center gap-4 text-[11px] text-[#8aa0a3]"><span className="flex items-center gap-1.5"><Clock3 className="h-3.5 w-3.5" />{quiz.timeLimit ? `${quiz.timeLimit} دقیقه` : "بدون زمان"}</span><span className="flex items-center gap-1.5"><Sparkles className="h-3.5 w-3.5" />مشاهده</span></div></button>)}</div> : <EmptyState title={teacher ? "هنوز آزمونی نساخته‌ای" : "هنوز آزمونی برایت نیست"} description={teacher ? "یک آزمون دستی بساز یا از یک مطلب درسی سؤال تولید کن." : "وقتی یک آزمون منتشرشده در دسترس باشد، اینجا می‌بینی."} />}</div>;
}
