import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { ArrowLeft, BookOpen, Brain, CalendarDays, ClipboardList, FileText, MessageCircle, NotebookPen, Sparkles, Target, WandSparkles } from "lucide-react";
import { Link } from "wouter";
import { PageHeader, StatCard, EmptyState } from "./Shared";

const actions = [{ href: "/tutor", title: "درس بده", sub: "مفهوم را بفهم", icon: MessageCircle, tone: "bg-[#e1f4f2] text-[#087f8c]" }, { href: "/solve", title: "حل کن", sub: "مسئله را تحلیل کن", icon: WandSparkles, tone: "bg-[#fff0df] text-[#d77b35]" }, { href: "/files", title: "از روی عکس بخون", sub: "فایل و عکس سؤال", icon: FileText, tone: "bg-[#e7f0ff] text-[#4c72bd]" }, { href: "/quizzes", title: "آزمون", sub: "خودت را بسنج", icon: ClipboardList, tone: "bg-[#eeeaff] text-[#7562c3]" }, { href: "/flashcards", title: "مرور", sub: "فلش‌کارت‌های من", icon: NotebookPen, tone: "bg-[#e3f4e9] text-[#4a9667]" }, { href: "/planner", title: "برنامه‌ریزی", sub: "هدف بعدی را بچین", icon: CalendarDays, tone: "bg-[#ffebec] text-[#bd5e69]" }];

export default function StudentDashboard() {
  const summary = trpc.dashboard.summary.useQuery(undefined, { retry: false });
  const profile = trpc.profile.me.useQuery(undefined, { retry: false });
  const name = profile.data?.name || "دوست مدادی";
  const data = summary.data;
  return <div><PageHeader eyebrow="داشبورد دانش‌آموز" title={`سلام ${name}! امروز چی می‌خوای یاد بگیری؟`} description="یک قدم کوچک هم می‌تواند شروع یک مسیر خوب باشد." action={<Link href="/tutor" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#087f8c] px-5 text-sm font-bold text-white shadow-sm transition hover:bg-[#076d78]"><Sparkles className="h-4 w-4" /> پرسش از مداد</Link>} />
    <section className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="گفت‌وگوهای یادگیری" value={data?.conversations ?? "—"} hint="گفت‌وگوهای ذخیره‌شده" icon={MessageCircle} tone="teal" /><StatCard label="آزمون‌های انجام‌شده" value={data?.quizzes ?? "—"} hint="نتیجه‌های واقعی تو" icon={ClipboardList} tone="orange" /><StatCard label="فلش‌کارت‌ها" value={data?.flashcards ?? "—"} hint="برای مرور آماده‌اند" icon={Brain} tone="blue" /><StatCard label="برنامه‌های فعال" value={data?.plans ?? "—"} hint="هدف‌های در حال پیگیری" icon={Target} tone="green" /></section>
    <section className="mb-8 rounded-[1.5rem] border border-[#cae7e4] bg-[#eaf8f6] p-5 sm:p-7"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white text-[#087f8c] shadow-sm"><Sparkles className="h-5 w-5" /></div><div><p className="text-sm font-black text-[#1d5d62]">پیشنهاد امروز مداد</p><p className="mt-2 text-sm leading-7 text-[#5d7a7d]">یک موضوع را انتخاب کن و با یک توضیح کوتاه شروع کن؛ لازم نیست از قبل همه‌چیز را بلد باشی.</p></div></div><Link href="/tutor" className="inline-flex items-center gap-2 self-start rounded-xl bg-white px-4 py-3 text-xs font-bold text-[#087f8c] shadow-sm transition hover:bg-[#f8ffff]">شروع گفت‌وگو <ArrowLeft className="h-4 w-4" /></Link></div></section>
    <div className="mb-10"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-black text-[#244c52]">میانبرهای یادگیری</h2><span className="text-xs text-[#84999c]">هر وقت خواستی شروع کن</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{actions.map(item => { const Icon = item.icon; return <Link key={item.href} href={item.href} className="interactive rounded-2xl border border-[#deeaeb] bg-white p-4"><div className={`mb-4 flex h-10 w-10 items-center justify-center rounded-xl ${item.tone}`}><Icon className="h-[18px] w-[18px]" /></div><p className="text-sm font-extrabold text-[#315a60]">{item.title}</p><p className="mt-1 text-[11px] text-[#8aa0a3]">{item.sub}</p></Link> })}</div></div>
    <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-[1.4rem] border border-[#deeaeb] bg-white p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-black text-[#244c52]">فعالیت‌های اخیر</h2><Link href="/progress" className="text-xs font-bold text-[#087f8c]">نمایش پیشرفت</Link></div>{data?.recentActivity?.length ? <div className="space-y-3">{data.recentActivity.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl bg-[#f7fafb] px-4 py-3"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#eaf8f6] text-[#087f8c]"><BookOpen className="h-4 w-4" /></div><div><p className="text-sm font-bold text-[#315a60]">{item.topic || item.subject || "فعالیت یادگیری"}</p><p className="mt-1 text-[11px] text-[#8aa0a3]">{item.type === "quiz_completed" ? "آزمون تکمیل شد" : item.type === "lesson_completed" ? "درس تکمیل شد" : "فعالیت ثبت‌شده"}</p></div></div><span className="text-[11px] text-[#9aabad]">{item.createdAt ? new Date(item.createdAt).toLocaleDateString("fa-IR") : "—"}</span></div>)}</div> : <EmptyState title="هنوز فعالیتی ثبت نشده" description="با اولین گفت‌وگو، آزمون یا برنامه‌ریزی، مسیر یادگیری‌ات اینجا شکل می‌گیرد." href="/tutor" actionLabel="شروع اولین گفت‌وگو" />}</section><section className="rounded-[1.4rem] border border-[#deeaeb] bg-white p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-black text-[#244c52]">برنامه‌های فعال</h2><Link href="/planner" className="text-xs font-bold text-[#087f8c]">برنامه جدید</Link></div>{data?.upcomingPlans?.length ? <div className="space-y-3">{data.upcomingPlans.map(plan => <div key={plan.id} className="rounded-xl border border-[#edf2f2] p-4"><div className="flex items-center justify-between"><p className="text-sm font-extrabold text-[#315a60]">{plan.title}</p><CalendarDays className="h-4 w-4 text-[#087f8c]" /></div><p className="mt-2 text-xs text-[#8aa0a3]">{plan.subject || "مطالعه آزاد"} {plan.dailyMinutes ? `• روزی ${plan.dailyMinutes} دقیقه` : ""}</p></div>)}</div> : <EmptyState title="هنوز برنامه‌ای نداری" description="برای امتحان بعدی یا یک هدف کوچک، برنامه‌ات را همین‌جا بساز." href="/planner" actionLabel="ساخت برنامه مطالعه" />}</section></div>
  </div>;
}
