import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { ArrowLeft, BookOpen, ClipboardList, FileText, Plus, Users } from "lucide-react";
import { Link } from "wouter";
import { PageHeader, StatCard, EmptyState } from "./Shared";

export default function TeacherDashboard() {
  const counts = trpc.teacher.counts.useQuery(undefined, { retry: false }); const classes = trpc.teacher.classes.useQuery(undefined, { retry: false }); const data = counts.data;
  return <div><PageHeader eyebrow="فضای معلم" title="داشبورد کلاس‌ها" description="کلاس، محتوا و سنجش را یکجا مدیریت کن؛ بدون از دست دادن تمرکز روی یادگیری." action={<Link href="/teacher/classes" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#087f8c] px-5 text-sm font-bold text-white shadow-sm transition hover:bg-[#076d78]"><Plus className="h-4 w-4" /> ساخت کلاس</Link>} /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="کلاس‌های من" value={data?.classes ?? "—"} hint="کلاس‌های ساخته‌شده" icon={Users} tone="teal" /><StatCard label="دانش‌آموزان" value={data?.students ?? "—"} hint="اعضای کلاس‌ها" icon={Users} tone="orange" /><StatCard label="درس‌ها" value={data?.lessons ?? "—"} hint="محتوای منتشرشده" icon={BookOpen} tone="blue" /><StatCard label="تکالیف" value={data?.assignments ?? "—"} hint="تکالیف ساخته‌شده" icon={ClipboardList} tone="green" /></section><div className="mt-7 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-[1.5rem] border border-[#deeaeb] bg-white p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-black text-[#315a60]">کلاس‌های اخیر</h2><p className="mt-1 text-xs text-[#8aa0a3]">فضای کلاس را برای ادامه مسیر انتخاب کن.</p></div><Link href="/teacher/classes" className="text-xs font-bold text-[#087f8c]">همه کلاس‌ها</Link></div>{classes.data?.length ? <div className="space-y-3">{classes.data.map(item => <Link href="/teacher/classes" key={item.id} className="flex items-center justify-between rounded-2xl border border-[#edf2f2] p-4 transition hover:border-[#bfe4e1]"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eaf8f6] text-[#087f8c]"><BookOpen className="h-4 w-4" /></div><div><p className="text-sm font-extrabold text-[#315a60]">{item.name}</p><p className="mt-1 text-xs text-[#8aa0a3]">{item.subject || "بدون موضوع"} • کد دعوت {item.inviteCode}</p></div></div><ArrowLeft className="h-4 w-4 text-[#9ab0b2]" /></Link>)}</div> : <EmptyState title="هنوز کلاسی نساخته‌ای" description="اولین کلاس را بساز تا انتشار درس و تکلیف را شروع کنی." href="/teacher/classes" actionLabel="ساخت اولین کلاس" />}</section><section className="rounded-[1.5rem] border border-[#dce8e9] bg-[#123f46] p-6 text-white"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/10 text-[#f4ae6e]"><FileText className="h-5 w-5" /></div><h2 className="mt-6 text-xl font-black">شروع سریع</h2><p className="mt-3 text-sm leading-7 text-[#b3d0d0]">یک کلاس بساز، یک درس اضافه کن و بعد از دانش‌آموزها دعوت کن تا داده‌های واقعی یادگیری شکل بگیرد.</p><div className="mt-7 space-y-2 text-xs text-[#c6e3e1]"><div className="rounded-xl bg-white/10 p-3">۱. ساخت کلاس و دریافت کد دعوت</div><div className="rounded-xl bg-white/10 p-3">۲. انتشار محتوای آموزشی</div><div className="rounded-xl bg-white/10 p-3">۳. سنجش و بازخورد</div></div></section></div></div>;
}
